/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2018 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include "rtctime.h"
#include "gate_control.h"

volatile bool gate_open = false;

ISR(RTC_CNT_vect)
{
    // PA1_toggle_level();
    RTC.CNT = 0;

    rtc_increment_overflow_counter();

    /* Interrupt flag has to be cleared manually */
    RTC.INTFLAGS = RTC_OVF_bm | RTC_CMP_bm;
}

ISR(TCB0_INT_vect)
{
    gate_ctrl_switch_state(gate_get_actual_state());

	/**
	 * The interrupt flag is cleared by writing 1 to it, or when the Capture register
	 * is read in Capture mode
	 */
	TCB0.INTFLAGS = TCB_CAPT_bm;
}

ISR(BOD_VLM_vect)
{
	/* Insert your BOD interrupt handling code here */
}

ISR(PORTA_PORT_vect)
{
    if (VPORTA_INTFLAGS & (1 << 7))
        gate_ctrl_switch_state(GATE_OPEN_TIME_WAIT);

    if (VPORTA_INTFLAGS & (1 << 2))
    {
        PA1_toggle_level();

        // first force a reset
        gate_ctrl_switch_state(GATE_CLOSED);

        gate_ctrl_switch_state(gate_get_actual_state());

    }

	/* Clear interrupt flags */
	VPORTA_INTFLAGS = (1 << 0) | (1 << 1) | (1 << 2) | (1 << 3) | (1 << 6) | (1 << 7);
}
